[package]
name = "phosphorus"
description = "Makes GL bindings for you."
version = "0.0.5-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/phosphorus"
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
magnesium = "0.0.4"
tinyvec = { version = "0.3", features =["alloc"] }

[dev-dependencies]
chlorine = "1"

[features]
default = []
