[package]
name = "phosphorus"
version = "0.0.4"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
hashbrown = "0.6"

[dev-dependencies]
chlorine = "1"

[features]
global_loader = []
struct_loader = []
trace_calls = []
error_checks = []
default = ["global_loader", "struct_loader", "trace_calls", "error_checks"]
