[package]
name = "phosphorus"
description = "Makes GL bindings for you."
version = "0.0.5-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/phosphorus"
edition = "2018"
license = "Zlib"

[dependencies]
magnesium = "*"
tinyvec = { version = "*", features =["alloc"] }

[dev-dependencies]
chlorine = "1"

[features]
global_loader = []
struct_loader = []
trace_calls = []
error_checks = []
default = ["global_loader", "struct_loader", "trace_calls", "error_checks"]
