[package]
name = "phosphorus"
version = "0.0.4-alpha"
authors = ["Lokathor <zefria@gmail.com>"]
edition = "2018"
license = "Zlib"

[dependencies]
hashbrown = "0.6"

[dev-dependencies]
chlorine = "1"

[features]
global_loader = []
struct_loader = []
default = ["global_loader", "struct_loader"]
