[package]
name = "phosphorus"
description = "Makes GL bindings for you."
version = "0.0.13-alpha.0"
authors = ["Lokathor <zefria@gmail.com>"]
repository = "https://github.com/Lokathor/phosphorus"
edition = "2018"
license = "Zlib OR Apache-2.0 OR MIT"

[dependencies]
magnesium = "1"
#chlorine = { version = "1.0.5", optional = true }
#log = { version = "0.4", optional = true }
#bytemuck = { version = "1", optional = true }

[features]
#default = ["struct_loader", "global_loader", "debug_trace_calls", "debug_automatic_glGetError", "inline", "inline_always", "chlorine", "log", "bytemuck"]
#struct_loader = []
#global_loader = []
#debug_trace_calls = []
#debug_automatic_glGetError = []
#inline = []
#inline_always = []
